version: '3'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test01
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
